name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: plant-site
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  deploy:
        needs: [build]
        runs-on: plant-site
        steps:
          - name: Clear cache
            run: docker builder prune -a
          - name: Build docker image
            run: docker build -t plant .
          - name: Stop current container
            run: docker stop plant
          - name: Run new container
            run: docker run -it -d -p 8080:80 --rm --name plant plant